### ISSUE TITLE
Ctrl + Alt + L - выравнивание кода

### ISSUE THREAD

**Issue by coursar** [Dinar-92/ATM#1]
https://github.com/Dinar-92/ATM/blob/1684b135f7147aabb327cbbd32d3846a178e80a0/src/Atm.java#L2-L19

**Comment by Dinar-92** [comment]
Код выровнен
https://github.com/Dinar-92/ATM/blob/64661a931a062a060eb2109b02d264d6a0ea0e3f/src/Atm.java#L1-L22
